baseURL: 'https://tkysela.cz'
languageCode: en
DefaultContentLanguage: en
title: Tomáš Kysela
theme: github.com/lxndrblz/anatole

summarylength: 10
enableEmoji: true
enableRobotsTXT: true

## Enable Disqus
# disqusShortname:

## Syntax highlighting
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true

localizedDates: true

markup:
  goldmark:
    renderer:
      unsafe: true

module:
  imports:
    - path: github.com/lxndrblz/anatole
      disable: false
