main:
  - name: O mně
    identifier: home
    weight: 100
    url: /

  - name: Příspěvky
    weight: 200
    identifier: posts
    url: /posts/

  - name: Portfolio
    weight: 300
    identifier: portfolio
    url: /portfolio/

  - name: Úspěchy
    weight: 400
    identifier: accomplishments
  - name: Ocenění
    weight: 410
    identifier: awards
    url: /awards/
    parent: accomplishments
  - name: Certifikace
    weight: 420
    identifier: certifications
    url: /certifications/
    parent: accomplishments

footer:
  - name: Made with Hugo
    weight: 1
    identifier: hugo
    url: https://gohugo.io

  - name: Theme Anatole
    weight: 2
    identifier: theme
    url: https://github.com/lxndrblz/anatole
