main:
  - name: About me
    identifier: about
    weight: 100
    url: /

  - name: Posts
    weight: 200
    identifier: post
    url: /posts/

  - name: Portfolio
    weight: 300
    identifier: portfolio
    url: /portfolio/

  - name: Accomplishments
    weight: 400
    identifier: accomplishments
  - name: Awards
    weight: 410
    identifier: awards
    url: /awards/
    parent: accomplishments
  - name: Certifications
    weight: 420
    identifier: certifications
    url: /certifications/
    parent: accomplishments

footer:
  - name: Made with Hugo
    weight: 1
    identifier: hugo
    url: https://gohugo.io

  - name: Theme Anatole
    weight: 2
    identifier: theme
    url: https://github.com/lxndrblz/anatole
